import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiRust,
  SiGo,
  SiCplusplus,
  SiC,
  SiSharp,
  SiSwift,
  SiKotlin,
  SiRuby,
  SiPhp,
  SiHtml5,
  SiCss3,
  SiReact,
  SiVuedotjs,
  SiSvelte,
  SiJest,
  SiNextdotjs,
  SiEslint,
  SiSupabase,
  SiTailwindcss,
  SiExpress,
  SiPrisma,
  SiMongodb,
  SiAstro,
  SiFastify,
  SiAxios,
  SiRedis,
  SiAmazon,
  SiVite,
  SiNodedotjs,
  SiPostcss,
  SiSqlite,
  SiVercel,
  SiArduino,
  SiSass,
  SiGrunt,
  SiAngular,
  SiChai,
} from "react-icons/si";
import { Code } from "lucide-react";
import type { IconType } from "react-icons";

type LanguageIconProps = {
  language: string;
  className?: string;
};

const languageIconMap: Record<string, IconType> = {
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Python: SiPython,
  Rust: SiRust,
  Go: SiGo,
  "C++": SiCplusplus,
  C: SiC,
  "C#": SiSharp,
  Swift: SiSwift,
  Kotlin: SiKotlin,
  Ruby: SiRuby,
  PHP: SiPhp,
  HTML: SiHtml5,
  CSS: SiCss3,
  React: SiReact,
  Vue: SiVuedotjs,
  Svelte: SiSvelte,
  Jest: SiJest,
  "Next.js": SiNextdotjs,
  ESLint: SiEslint,
  Supabase: SiSupabase,
  "React Testing Library": SiReact,
  "React Icons": SiReact,
  "Tailwind CSS": SiTailwindcss,
  Express: SiExpress,
  Prisma: SiPrisma,
  MongoDB: SiMongodb,
  Astro: SiAstro,
  Fastify: SiFastify,
  Axios: SiAxios,
  Redis: SiRedis,
  AWS: SiAmazon,
  Vite: SiVite,
  "Node Fetch": SiNodedotjs,
  "Radix UI": SiReact,
  "Lucide Icons": SiReact,
  PostCSS: SiPostcss,
  Turbopack: SiNodedotjs,
  Zod: SiTypescript,
  "shadcn/ui": SiReact,
  SQLite: SiSqlite,
  "date-fns": SiJavascript,
  dotenv: SiNodedotjs,
  "Moment.js": SiJavascript,
  "React Router": SiReact,
  "Styled Components": SiReact,
  "Framer Motion": SiReact,
  Zustand: SiReact,
  Lodash: SiJavascript,
  Redux: SiReact,
  Vercel: SiVercel,
  "TanStack Query": SiReact,
  Arduino: SiArduino,
  "Adafruit Libraries": SiArduino,
  "React Hook Form": SiReact,
  Sass: SiSass,
  Grunt: SiGrunt,
  "WiFi (Arduino)": SiArduino,
  Angular: SiAngular,
  Chai: SiChai,
};

const languageColorMap: Record<string, string> = {
  TypeScript: "#3178c6",
  JavaScript: "#f7df1e",
  Python: "#3776ab",
  Rust: "#ce412b",
  Go: "#00add8",
  "C++": "#00599c",
  C: "#555555",
  "C#": "#239120",
  Swift: "#fa7343",
  Kotlin: "#7f52ff",
  Ruby: "#cc342d",
  PHP: "#777bb4",
  HTML: "#e34c26",
  CSS: "#1572b6",
  React: "#61dafb",
  Vue: "#4fc08d",
  Svelte: "#ff3e00",
  Jest: "#15c213",
  "Next.js": "#000000",
  ESLint: "#4b32c3",
  Supabase: "#3ecf8e",
  "React Testing Library": "#61dafb",
  "React Icons": "#61dafb",
  "Tailwind CSS": "#06b6d4",
  Express: "#000000",
  Prisma: "#2d3748",
  MongoDB: "#13aa52",
  Astro: "#ff5d01",
  Fastify: "#000000",
  Axios: "#671ddf",
  Redis: "#dc382d",
  AWS: "#ff9900",
  Vite: "#646cff",
  "Node Fetch": "#68a063",
  "Radix UI": "#61dafb",
  "Lucide Icons": "#61dafb",
  PostCSS: "#dd3735",
  Turbopack: "#0078e6",
  Zod: "#3178c6",
  "shadcn/ui": "#61dafb",
  SQLite: "#003b57",
  "date-fns": "#f7df1e",
  dotenv: "#edb200",
  "Moment.js": "#f7df1e",
  "React Router": "#61dafb",
  "Styled Components": "#db7093",
  "Framer Motion": "#0055ff",
  Zustand: "#f7df1e",
  Lodash: "#3c3c3c",
  Redux: "#764abc",
  Vercel: "#000000",
  "TanStack Query": "#61dafb",
  Arduino: "#00878f",
  "Adafruit Libraries": "#00878f",
  "React Hook Form": "#61dafb",
  Sass: "#c69",
  Grunt: "#fca53b",
  "WiFi (Arduino)": "#00878f",
  Angular: "#dd0031",
  Chai: "#a40802",
};

export const LanguageIcon = ({ language, className = "h-5 w-5" }: LanguageIconProps) => {
  const Icon = languageIconMap[language];
  const color = languageColorMap[language];

  if (Icon) {
    return (
      <span title={language}>
        <Icon className={className} style={{ color }} />
      </span>
    );
  }

  // Fallback to generic code icon
  return (
    <span title={language}>
      <Code className={className} />
    </span>
  );
};
